# Домашнее задание 2 (10 баллов).

*Все задания ниже имеют равный вес*

Код для импорта мы написали за вас (не благодарите, нам не трудно). Дальше код будете писать вы.

[Тут](https://habr.com/ru/companies/ruvds/articles/494720/) шпора по pandas. За основу домашнего задания взят ноутбук [отсюда](https://rutube.ru/video/f884aa6ed5f94120b7304506042fe5bb/) (не подглядывайте!).

In [ ]:
import pandas as pd
import numpy as np

#### Описание данных

Автор д/з - плохой человек, который не стал переводить описание с мотивировкой, что весь DS на английском. Так что описание полей будет на английском:

1. Account ID
- Description: A unique identifier for each social media account in the dataset.
- Type: Integer
- Example: 1, 2, 3, …
2. Username
- Description: The username or handle of the social media account.
- Type: String
- Example: john_doe, tech_guru_22, fitness_freak
3. Platform
- Description: The social media platform the account is using (Instagram, Twitter, Facebook, TikTok, LinkedIn).
- Type: Categorical (String)
- Example: Instagram, Twitter, Facebook, TikTok, LinkedIn
4. Follower Count
- Description: The total number of followers the account has.
- Type: Integer
- Example: 1500, 245000, 78000
5. Posts Per Week
- Description: The average number of posts the account creates per week.
- Type: Integer
- Example: 3, 5, 7
6. Engagement Rate
- Description: The percentage of interactions (likes, comments, shares) relative to the follower count. This is a measure of how engaging the content is.
- Type: Float
- Range: 0.01 to 0.15
- Example: 0.045 (4.5% engagement rate)
7. Ad Spend (USD)
- Description: The monthly amount spent on advertising or promoting posts.
- Type: Float
- Example: 150.75, 850.00, 300.50
8. Conversion Rate
- Description: The percentage of users who take a desired action (e.g., clicking a link, signing up, etc.) after interacting with an ad.
- Type: Float
- Range: 0.01 to 0.05 (1% to 5% conversion rate)
- Example: 0.025 (2.5% conversion rate)
9. Campaign Reach
- Description: The total number of unique users reached by the user’s campaigns in a given month.
- Type: Integer
- Example: 5000, 20000, 15000

#### Задание 0

Подгрузите данные. Да-да, за чтение таблицы баллов не будет))

**Hint**: [pd.read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)

In [ ]:
df = pd.read_csv("data.csv")

In [ ]:
df

,Account ID,Username,Platform,Follower Count,Posts Per Week,Engagement Rate,Ad Spend (USD),Conversion Rate,Campaign Reach
0,1,harrislisa,TikTok,54217,3,0.0986,538.10,0.0490,1308
1,2,rhicks,LinkedIn,987518,5,0.0834,479.24,0.0174,13302
2,3,qthomas,Facebook,218870,3,0.1020,150.36,0.0318,11043
3,4,carlosholt,Instagram,207432,6,0.0834,932.62,0.0400,12074
4,5,parsonsashley,Facebook,350204,2,0.0642,504.44,0.0463,14083
...,...,...,...,...,...,...,...,...,...
9995,9996,sbyrd,TikTok,388169,6,0.0642,362.91,0.0108,45091
9996,9997,jacksongerald,TikTok,150775,1,0.0642,177.92,0.0262,33084
9997,9998,eryan,Twitter,427451,5,0.0834,432.65,0.0402,12484
9998,9999,barbara57,LinkedIn,132884,4,0.0986,892.99,0.0329,35766
9999,10000,nbutler,Facebook,725253,2,0.0642,878.87,0.0420,13012

#### Задание 1

Колонка `Platform` содержит название различных платформ. Давайте представим, что в них есть некоторое отношение порядка. Закодируйте каждую платформу целым числом (от 0 до N) и положите этот "код" в новую колонку `Platform_Code`. Теперь вычислите корреляцию Спирмена между всеми парами колонок в датасете (результатом будет таблица корреляций). В качестве ответа выведите значение корреляции `Platform_Code` с `Engagement Rate`. Можете после вывода числа еще коротко написать, что оно означает (нет, это не оценивается).

**Hint**: [pd.factorize](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.factorize.html), [pd.DataFrame.select_dtypes](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.select_dtypes.html), [pd.DataFrame.corr](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html).

In [ ]:
df['Platform_Code'] = (pd.factorize( df['Platform'] , sort = False , use_na_sentinel = True , size_hint = None ))[0]

In [ ]:
df

,Account ID,Username,Platform,Follower Count,Posts Per Week,Engagement Rate,Ad Spend (USD),Conversion Rate,Campaign Reach,Platform_Code
0,1,harrislisa,TikTok,54217,3,0.0986,538.10,0.0490,1308,0
1,2,rhicks,LinkedIn,987518,5,0.0834,479.24,0.0174,13302,1
2,3,qthomas,Facebook,218870,3,0.1020,150.36,0.0318,11043,2
3,4,carlosholt,Instagram,207432,6,0.0834,932.62,0.0400,12074,3
4,5,parsonsashley,Facebook,350204,2,0.0642,504.44,0.0463,14083,2
...,...,...,...,...,...,...,...,...,...,...
9995,9996,sbyrd,TikTok,388169,6,0.0642,362.91,0.0108,45091,0
9996,9997,jacksongerald,TikTok,150775,1,0.0642,177.92,0.0262,33084,0
9997,9998,eryan,Twitter,427451,5,0.0834,432.65,0.0402,12484,4
9998,9999,barbara57,LinkedIn,132884,4,0.0986,892.99,0.0329,35766,1
9999,10000,nbutler,Facebook,725253,2,0.0642,878.87,0.0420,13012,2

In [ ]:
cor = df.select_dtypes(include = {'int64', 'float64'}).corr('spearman')
cor

,Account ID,Follower Count,Posts Per Week,Engagement Rate,Ad Spend (USD),Conversion Rate,Campaign Reach,Platform_Code
Account ID,1.000000,0.002866,-0.003058,0.000611,-0.004928,0.005095,-0.006896,-0.005208
Follower Count,0.002866,1.000000,-0.004853,-0.016428,-0.004516,0.014002,-0.020816,0.010304
Posts Per Week,-0.003058,-0.004853,1.000000,0.016908,-0.001298,-0.011176,0.003364,-0.011840
Engagement Rate,0.000611,-0.016428,0.016908,1.000000,0.007712,-0.006964,0.013299,0.031382
Ad Spend (USD),-0.004928,-0.004516,-0.001298,0.007712,1.000000,0.011723,0.011008,-0.014922
Conversion Rate,0.005095,0.014002,-0.011176,-0.006964,0.011723,1.000000,-0.008647,0.007528
Campaign Reach,-0.006896,-0.020816,0.003364,0.013299,0.011008,-0.008647,1.000000,0.012024
Platform_Code,-0.005208,0.010304,-0.011840,0.031382,-0.014922,0.007528,0.012024,1.000000

In [ ]:
print(cor['Platform_Code']['Engagement Rate']) # ну что-то они почти не коррелируют

0.03138169529349812

#### Задание 2

Теперь посмотрите на столбец `Follower Count`. В нем какие-то числа. Иногда бывает полезно провести дискретизацию такого признака. Разбейте все значения в столбце на 4 группы: "Low", "Medium", "High", "Very High". Каждая группа включает в себя новые 25% данных. То есть, Low включает в себя 25% самых маленьких значений признака и так далее. Положите значения "Low", "Medium", "High" или "Very High" для каждого сэмпла датасета в новую колонку `Follower_Bin`. Теперь посчитайте среднее значение `Engagement Rate` для каждой категории из `Follower_Bin`. В качестве ответа выведите значение для категории "High".

**Hint**: [pd.qcut](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.qcut.html), [pd.groupby](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html), [pd.DataFrame.mean](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mean.html)

In [ ]:
types = ["Low", "Medium", "High", "Very High"]
quant = pd.qcut(df['Follower Count'], 4, ["Low", "Medium", "High", "Very High"])
quant

0             Low
1       Very High
2             Low
3             Low
4          Medium
          ...
9995       Medium
9996          Low
9997       Medium
9998          Low
9999         High
Name: Follower Count, Length: 10000, dtype: category
Categories (4, object): ['Low' < 'Medium' < 'High' < 'Very High']

In [ ]:
df['Follower_Bin'] = quant

In [ ]:
groups = df.groupby('Follower_Bin')["Engagement Rate"].mean()
groups

/tmp/ipython-input-2986605300.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  groups = df.groupby('Follower_Bin')["Engagement Rate"].mean()

Follower_Bin
Low          0.087032
Medium       0.086858
High         0.086550
Very High    0.086505
Name: Engagement Rate, dtype: float64

In [ ]:
print(groups['High'])

0.08655032

#### Задание 3

Иногда бывает полезно превратить широкую таблицу в длинную (например, для визуализаций сразу нескольких признаков на одной картинке). Да, звучит странно, но именно этим вы сейчас и займетесь. Сделайте новый датафрейм `melted_df`, в который вы поместите каждый сэмпл датасета 6 раз: по одному разу на значение из 'Follower Count', 'Posts Per Week', 'Ad Spend (USD)', 'Conversion Rate', 'Engagement Rate' и 'Campaign Reach'. То есть, вы берете сэмпл из датасета (строку) и превращаете ее в 6 отдельных строк. Каждая отдельная строка в столбце `Metric` имеет имя из предложенного списка 5 признаков, а в столбце `Value` - значение данного сэмпла по этому признаку. Значение `Platform` повторяется в этих 6 строках.

Иначе говоря,

```json
{
    "Account ID": 1,
    "Username": "harrislisa",
    "Platform": "TikTok",
    "Follower Count": 54217,
    "Posts Per Week": 3,
    "Engagement Rate": 0.0986,
    "Ad Spend (USD)": 538.1,
    "Conversion Rate": 0.049,
    "Campaign Reach": 1308,
    "Platform_Code": 0,
    "Follower_Bin": "Low"
}
```

превращается в

```json
{
    "Platform": "TikTok",
    "Metric": "Follower Count",
    "Value": 54217,
},
{
    "Platform": "TikTok",
    "Metric": "Posts Per Week",
    "Value": 3,
}, ...
```

Для каждого уникальной пары значений (`Platform`, `Metric`) посчитайте моду среди всех значений `Value` для этой пары, результат сделайте списком и оставьте только наибольшее. В качестве ответа выведите сумму полученных мод (сумму всех значений в столбце `Value` уже после вычисления мод). Иначе говоря, выведите сумму всех мод значений для всех уникальных пар (`Platform`, `Metric`).

**Hint**: [pd.melt](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.melt.html), [pd.DataFrame.mode](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mode.html), [pd.DataFrameGroupBy.agg](https://pandas.pydata.org/docs/dev/reference/api/pandas.core.groupby.DataFrameGroupBy.agg.html)

In [ ]:
melting = pd.melt(df, id_vars=["Platform"], value_vars=['Follower Count', 'Posts Per Week', 'Ad Spend (USD)', 'Conversion Rate', 'Engagement Rate', 'Campaign Reach'], var_name="Metric", value_name="Value")

In [ ]:
melting

        Platform          Metric     Value
0         TikTok  Follower Count   54217.0
1       LinkedIn  Follower Count  987518.0
2       Facebook  Follower Count  218870.0
3      Instagram  Follower Count  207432.0
4       Facebook  Follower Count  350204.0
...          ...             ...       ...
59995     TikTok  Campaign Reach   45091.0
59996     TikTok  Campaign Reach   33084.0
59997    Twitter  Campaign Reach   12484.0
59998   LinkedIn  Campaign Reach   35766.0
59999   Facebook  Campaign Reach   13012.0

[60000 rows x 3 columns]

In [ ]:
modes = melting.groupby(['Platform',  'Metric']).agg(lambda s: s.mode().max())
modes

                                 Value
Platform  Metric
Facebook  Ad Spend (USD)      421.5600
          Campaign Reach    49860.0000
          Conversion Rate       0.0186
          Engagement Rate       0.0856
          Follower Count   350858.0000
          Posts Per Week        5.0000
Instagram Ad Spend (USD)      878.6800
          Campaign Reach    48629.0000
          Conversion Rate       0.0274
          Engagement Rate       0.0986
          Follower Count   999726.0000
          Posts Per Week        5.0000
LinkedIn  Ad Spend (USD)      783.6000
          Campaign Reach    14912.0000
          Conversion Rate       0.0186
          Engagement Rate       0.0642
          Follower Count    92848.0000
          Posts Per Week        6.0000
TikTok    Ad Spend (USD)      951.6500
          Campaign Reach    48053.0000
          Conversion Rate       0.0227
          Engagement Rate       0.0856
          Follower Count   700758.0000
          Posts Per Week        6.0000
Twitter   Ad Spend (USD)      696.4300
          Campaign Reach    46757.0000
          Conversion Rate       0.0283
          Engagement Rate       0.1020
          Follower Count   744125.0000
          Posts Per Week        5.0000

In [ ]:
sum(modes['Value'])

3100285.4716

#### Задание 4

А теперь хочется посмотреть на самые популярные аккаунты на разных платформах. Для каждой платформы отсортируйте датафрейм по убыванию количества подписчиков (`Follower Count`) - да, без циклов, сразу для всех платформ сделать сортировку, а затем оставьте только первые три записи для каждой платформы - это и будут три самых популярных аккаунта для каждой платформы. В качестве ответа выведите саму таблицу и минимальное значение `Follower Count` в ней.

**Hint**: к *groupby* можно применять функции - это эквивалентно применению функции к каждой "группе" внутри groupby-объекта. Читайте [про применение apply к датафрейму после groupby](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#flexible-apply).

In [ ]:
top3 = df.groupby("Platform").apply(lambda g: g.sort_values("Follower Count", ascending=False)["Follower Count"].head(3))
top3

/tmp/ipython-input-4074184950.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top3 = df.groupby("Platform").apply(lambda g: g.sort_values("Follower Count", ascending=False)["Follower Count"].head(3))

Platform
Facebook   2403    999982
           7350    997915
           1689    997512
Instagram  8685    999726
           3965    999351
           2189    997844
LinkedIn   3039    999055
           6359    998968
           2159    998925
TikTok     5838    999739
           4234    999234
           2575    998623
Twitter    4920    999919
           9684    999442
           7576    998216
Name: Follower Count, dtype: int64

In [ ]:
top3.min()

997512

#### Задание 5

Хочется посчитать какую-то метрику. Мы хотим посмотреть, на отношение разности суммы подписчиков аккаунтов с высокой и низкой конверсией к суммарному охвату рекламы на каждой платформе. То есть, мы делим аккаунты на две группы: высокая и низка конверсия. Затем мы смотрим на то, на сколько сильно влияние аккаунтов с высокой конверсией по сравнению с аккаунтами с низкой конверсией.

Давайте определим *Conversion Influence* следущим образом:

$$Conversion Influence = \frac{Total Follower\ Count (High) - Total Follower\ Count (Low)}{Total Campaign Reach (High)+Total Campaign Reach (Low)}$$

Считать эту метрику мы будет для каждой `Platform`. В этой формуле High - это значения всех сэмплов датасета, в которых `Conversion Rate` больше медианы, а `Low` - не более медианы. `Total Feature` - это суммарное количество значений `Feature` либо по `High` сэмплам, либо по `Low`.

Чтобы постоянно не пересчитывать, где High. где Low, сделайте новую колонку в датасете `Conversion_Category`. Положите в нее для каждой строки либо High, либо Low.

Выведите платформу с самым большим `Conversion Influence`.

**Hint**: данное задание не про *groupby*, а скорее про [pd.pivot_table](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html). Сделайте сводную таблицу, по которой уже можно посчитать суммы, а затем подставить их в формулы.

In [ ]:
median = df["Conversion Rate"].median()
pt = pd.pivot_table(
    df.assign(Conversion_Category=np.where(df["Conversion Rate"] > median, "High", "Low")),
    index="Platform",
    columns="Conversion_Category",
    values=["Follower Count", "Campaign Reach"],
    aggfunc="sum",
    fill_value=0
)

In [ ]:
pt["Conversion Influence"] = (pt[("Follower Count", "High")] - pt[("Follower Count", "Low")]) / (pt[("Campaign Reach", "High")] + pt[("Campaign Reach", "Low")])
pt

                    Campaign Reach           Follower Count             \
Conversion_Category           High       Low           High        Low
Platform
Facebook                  26096572  25635749      512439819  499712373
Instagram                 24250993  26482804      487970573  524726855
LinkedIn                  25186827  25147594      509450797  499766430
TikTok                    24253556  25091283      495899696  491110679
Twitter                   26376400  24566705      536955379  481382949

                    Conversion Influence
Conversion_Category
Platform
Facebook                        0.246025
Instagram                      -0.724493
LinkedIn                        0.192400
TikTok                          0.097052
Twitter                         1.090872

In [ ]:
pt['Conversion Influence'].idxmax()

'Twitter'

#### Задание 6

Мы знаем, что вам понравилось считать метрики по формуле. Давайте закрепим этот успех. Теперь для каждой платформы посчитаем, на сколько эффективна реклама в разрезе трех последовательных записей в датасете.

Для каждой платформы отсортируйте записи в порядке убывания `Posts Per Week`. Будто бы аккаунты, которые постят чаще, используют более "активные" стратегии по рекламе. Теперь посчитайте *скользущие суммы с окном 3* по `Campaign Reach` и `Ad Spend (USD)`. Скользящая сумма с окном N - это вы идете по массиву, берете все последовательные тройки записей и суммируете их. Для первых двух записей троек не найдется. Для них скользящее среднее - NaN, что нам не помешает.

Теперь для каждого окна посчитайте

$$Rolling Efficiency Ratio = \frac{Rolling Sum of Campaign Reach}{Rolling Sum of Ad Spend}$$

По сути, для каждого окна вы посчитаете сколько пользователе привлеклось за один доллар, потреченный на рекламу, в данном окне. Понятно, что значений будет столько, сколько окон. Нам интересно максимально значение такой эффективности для каждой платформы.

В качестве ответа выведите название платформы с наибольшей максимальной эффективность и наименьшей (два названия, не одно, не три, ровно два).

**Hint**: окна можно делать через [pd.DataFrame.rolling](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rolling.html).

In [ ]:
df_s = df.sort_values(["Platform", "Posts Per Week"], ascending=False)

In [ ]:
rolling_income = df_s.groupby("Platform")["Campaign Reach"].rolling(window=3).sum()
rolling_outcome = df_s.groupby("Platform")["Ad Spend (USD)"].rolling(window=3).sum()

In [ ]:
ratio = (rolling_income / rolling_outcome).rename("Ratio")
ratio

Platform
Facebook  25            NaN
          57            NaN
          71      59.346993
          76      41.385779
          115     59.645037
                    ...
Twitter   9909    50.735271
          9922    43.586057
          9926    29.493874
          9944    29.557433
          9962    28.959782
Name: Ratio, Length: 10000, dtype: float64

In [ ]:
maxef = ratio.groupby(level=0).max().rename("MaxRollingEfficiency")
maxef

Platform
Facebook     388.513469
Instagram    371.822908
LinkedIn     261.489362
TikTok       259.209914
Twitter      341.152664
Name: MaxRollingEfficiency, dtype: float64

In [ ]:
maxef.idxmax()

'Facebook'

In [ ]:
maxef.idxmin()

'TikTok'

#### Задание 7

Это еще не все прекрасные функции pandas, которые мы хотим вам показать. Теперь вы посчитаете, сколько аккаунтов на каждой платформе одновременно лучшие по `Engagement Rate` и `Conversion Rate`.

Сделайте два отдельных суб-сета. В одном оставьте для каждой платфмормы один топовый аккаунт по `Engagement Rate`, в другом - по `Conversion Rate`. Соедините эти два подмножества по столбцу `Platform` так, что в одно строке есть описание сразу двух аккаунтов-лидеров. Теперь посмотрите равны ли имена аккаунтов в одной строке. Выведите количество строк, в которых названия аккаунтов совпадают.

In [ ]:
etop = df.groupby("Platform")['Engagement Rate'].idxmax()
etop

Platform
Facebook      2
Instagram    59
LinkedIn     72
TikTok       22
Twitter      94
Name: Engagement Rate, dtype: int64

In [ ]:
ctop = df.groupby("Platform")['Conversion Rate'].idxmax()
ctop

Platform
Facebook     3464
Instagram    2863
LinkedIn     8016
TikTok        284
Twitter      5992
Name: Conversion Rate, dtype: int64

In [ ]:
eng_user = df.loc[etop].set_index("Platform")["Username"]
conv_user = df.loc[ctop].set_index("Platform")["Username"]

In [ ]:
res = pd.concat([eng_user.rename("Top_Eng"), conv_user.rename("Top_Conv")], axis=1)

In [ ]:
res

                 Top_Eng       Top_Conv
Platform
Facebook         qthomas      michael55
Instagram   jaimeedwards  aprilwilliams
LinkedIn         allen72         jeff87
TikTok        carlosholt   robertmorris
Twitter    marquezedward      trobinson

In [ ]:
(res["Top_Eng"] == res["Top_Conv"]).sum()

np.int64(0)

#### Задание 8

Давайте теперь что-то попроще сделаем. Например, посчитаем отношение суммарного количества подписчиков на аккаунтах с высокой конверсией к такой же сумме в аккаунтах с низкой конверсией (очевидно, для каждой платформы). По сути, мы просто хотим получить число, которое характеризует, на сколько сильно аккаунты с высокой конверсией "доминируют" над аккаунтами с низкой конверсией в плане количества подписчиков.

Высокой конверсией будем считать конверсию больше средней. Остальное - низкая. Посчитайте суммы подписчиков для каждой платформы, поделите одно на другое и выведите разницу между самым большим значением и самым маленьким, а также платформы, которые соотвутствуют этим значениям.

Используйте магическую команду `%%time`, чтобы замерить, сколько времени ушло на исполнение вашего pandas-скрипта.

In [ ]:
%%time
median = df["Conversion Rate"].mean()
pt2 = pd.pivot_table(
    df.assign(Conversion_Category=np.where(df["Conversion Rate"] > median, "High", "Low")),
    index="Platform",
    columns="Conversion_Category",
    values=["Follower Count"],
    aggfunc="sum",
    fill_value=0
)
pt2['ratio'] = pt2['Follower Count', 'High'] / pt2['Follower Count', 'Low']
max_p = pt2['ratio'].idxmax()
min_p = pt2['ratio'].idxmin()

CPU times: user 16.3 ms, sys: 833 µs, total: 17.2 ms
Wall time: 17.4 ms

In [ ]:
pt2

                    Follower Count                ratio
Conversion_Category           High        Low
Platform
Facebook                 491799506  520352686  0.945127
Instagram                468232352  544465076  0.859986
LinkedIn                 490706904  518510323  0.946378
TikTok                   482930355  504080020  0.958043
Twitter                  518386631  499951697  1.036873

In [ ]:
print(max_p, min_p, pt2['ratio'][max_p] - pt2['ratio'][min_p])

Twitter Instagram 0.17688741338715763

#### Задание 9

А теперь решите задание 8 чисто питоном. Никаких функций и методов pandas. Только питоновские циклы. Замерьте время выполнения кода. Наконец, сравните время в задании 8 и 9. Напишите ниже, кто же победил: чистый python и pandas?

**Hint**: Чтобы итерироваться по датафрейму, можно из него сделать генератор через [pd.DataFrame.iterrows](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iterrows.html) или [pd.DataFrame.itertuples](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples). К слову, это не все способы итерироваться по датафрейму.

In [ ]:
%%time
mean = 0
for i in df["Conversion Rate"]:
  mean+=i
mean /=len(df["Conversion Rate"])
lows = dict()
highs = dict()
plat = ['Facebook', 'Instagram', 'LinkedIn', 'TikTok', 'Twitter']
for i  in plat:
  lows[i] = 0
  highs[i] = 0
for i in range(len(df["Conversion Rate"])):
  if df["Conversion Rate"][i] > mean:
    highs[df["Platform"][i]] += df["Follower Count"][i]
  else:
    lows[df["Platform"][i]] += df["Follower Count"][i]
print(highs)
print(lows)
rat = []
for i in plat:
  rat.append(highs[i] / lows[i])
print(max(rat) - min(rat))
for i in range(5):
  if(rat[i] == max(rat)):
    print(plat[i])

for i in range(5):
  if(rat[i] == min(rat)):
    print(plat[i])

{'Facebook': np.int64(491799506), 'Instagram': np.int64(468232352), 'LinkedIn': np.int64(490706904), 'TikTok': np.int64(482930355), 'Twitter': np.int64(518386631)}
{'Facebook': np.int64(520352686), 'Instagram': np.int64(544465076), 'LinkedIn': np.int64(518510323), 'TikTok': np.int64(504080020), 'Twitter': np.int64(499951697)}
0.17688741338715763
Twitter
Instagram
CPU times: user 156 ms, sys: 1.68 ms, total: 158 ms
Wall time: 158 ms

Получилось всего лишь в 9 раз медленнее на питоне. Зато своё